language: minimal
services:
- docker

cache:
  directories:
  - ubuntu-base/build

env:
- IMAGE=ubuntu-base VERSION=18.10
- IMAGE=ubuntu-base VERSION=18.04

install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
- make -C $IMAGE build

deploy:
- provider: script
  script: make -C $IMAGE push-latest
- provider: script
  script: make -C $IMAGE push-tag REVISION=$TRAVIS_TAG
  on:
    tags: true
